apiVersion: batch/v1
kind: Job
metadata:
  name: populate-db
  labels:
    app: db-backup-restore
spec:
  template:
    spec:
      containers:
        - name: populate-bot
          image: liupengfei99/db_backup_restore:main
          env:
            - name: BACKUP_FILE
              value: "s3://projet-formation/diffusion/sda/06_SQL/north_wind.sql"  # the full path of the db backup file, example: s3://path/to/sql_backup/2022-01-12_test_pg_bck.sql
          envFrom:
            - configMapRef:
                name: dbsavior-job-init-configmap
            - secretRef:
                name: dbsavior-job-s3-secrets
          command: [sh, -c]
          args: ["python dbsavior/main.py --db_type postgres --storage_type s3 --action populate --db_login $DB_LOGIN 
                --db_pwd $DB_PWD --db_host $DB_HOST --db_port $DB_PORT
                --backup_file $BACKUP_FILE --target_db $TARGET_DB"]
      restartPolicy: Never
  completions: 1

  parallelism: 1
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 150
  backoffLimit: 1